@extends('layouts.app')
@section('title', 'New Issue')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h3 mb-0">New Issue</h1><a href="{{ route('issues.index') }}" class="btn btn-outline-secondary">Back</a></div>
<div class="card border-0 shadow-sm"><div class="card-body">
<form action="{{ route('issues.store') }}" method="POST">@csrf
<div class="row g-3">
<div class="col-md-6"><label class="form-label">Project *</label><select class="form-select @error('project_id') is-invalid @enderror" name="project_id" required id="issue-project">@foreach($projects as $p)<option value="{{ $p->id }}" {{ old('project_id', request('project_id')) == $p->id ? 'selected' : '' }}>{{ $p->name }}</option>@endforeach</select>@error('project_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Issue type *</label><select class="form-select @error('issue_type_id') is-invalid @enderror" name="issue_type_id" required>@foreach($issueTypes as $t)<option value="{{ $t->id }}" {{ old('issue_type_id') == $t->id ? 'selected' : '' }}>{{ $t->name }}</option>@endforeach</select>@error('issue_type_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12"><label class="form-label">Summary *</label><input type="text" class="form-control @error('summary') is-invalid @enderror" name="summary" value="{{ old('summary') }}" required maxlength="255">@error('summary')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control @error('description') is-invalid @enderror" name="description" rows="4">{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Priority</label><select class="form-select @error('priority_id') is-invalid @enderror" name="priority_id"><option value="">— None —</option>@foreach($priorities as $p)<option value="{{ $p->id }}" {{ old('priority_id') == $p->id ? 'selected' : '' }}>{{ $p->name }}</option>@endforeach</select>@error('priority_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Status</label><select class="form-select @error('status_id') is-invalid @enderror" name="status_id"><option value="">— None —</option>@foreach($statuses as $s)<option value="{{ $s->id }}" {{ old('status_id') == $s->id ? 'selected' : '' }}>{{ $s->name }}</option>@endforeach</select>@error('status_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Reporter</label><select class="form-select @error('reporter_id') is-invalid @enderror" name="reporter_id"><option value="">— None —</option>@foreach($users as $u)<option value="{{ $u->id }}" {{ old('reporter_id', auth()->id()) == $u->id ? 'selected' : '' }}>{{ $u->display_name ?? $u->username }}</option>@endforeach</select>@error('reporter_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Assignee</label><select class="form-select @error('assignee_id') is-invalid @enderror" name="assignee_id"><option value="">— None —</option>@foreach($users as $u)<option value="{{ $u->id }}" {{ old('assignee_id') == $u->id ? 'selected' : '' }}>{{ $u->display_name ?? $u->username }}</option>@endforeach</select>@error('assignee_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Story points</label><input type="number" step="any" class="form-control @error('story_points') is-invalid @enderror" name="story_points" value="{{ old('story_points') }}">@error('story_points')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Due date</label><input type="date" class="form-control @error('due_date') is-invalid @enderror" name="due_date" value="{{ old('due_date') }}">@error('due_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Parent issue</label><select class="form-select @error('parent_issue_id') is-invalid @enderror" name="parent_issue_id"><option value="">— None —</option>@foreach($parentIssues as $pi)<option value="{{ $pi->id }}" {{ old('parent_issue_id') == $pi->id ? 'selected' : '' }}>{{ $pi->issue_key }} — {{ Str::limit($pi->summary, 30) }}</option>@endforeach</select>@error('parent_issue_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label">Labels</label><select class="form-select @error('label_ids') is-invalid @enderror" name="label_ids[]" multiple>@foreach($labels as $l)<option value="{{ $l->id }}" {{ in_array($l->id, old('label_ids', [])) ? 'selected' : '' }}>{{ $l->name }}</option>@endforeach</select><small class="text-muted">Hold Ctrl to select multiple</small>@error('label_ids')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<button type="submit" class="btn btn-primary mt-3">Create</button>
</form></div></div>
@endsection
